# Welcome to our Lab practice!

This lab is all about the package, Numpy. Are you ready? Let's go!

You will find some small tasks in sections below. 

> Try to figure out by yourself, or search for references. Being able to search and find information needed is an important skill that benefits you and your career for a long time.





## Import the package and rename it as np

In [3]:
import numpy as np

## Array Creation

### Task: Create a numpy array from a list of integers

In [6]:
list = [1,2,3,4,5,6]
a = np.array(list)
a

array([1, 2, 3, 4, 5, 6])

### Task: Create a numpy array of size 6, filled with zeros

In [8]:
b = np.zeros(6, dtype = int)
b

array([0, 0, 0, 0, 0, 0])

### Task: Create a numpy array of size 6, filled with ones

In [10]:
c = np.ones(6, dtype = float)
c

array([1., 1., 1., 1., 1., 1.])

### Task: Create a numpy array with values from 0 to 10

In [12]:
d = np.arange(10, dtype = int)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Task: Create a numpy matrix of 2*3 integers, filled with zeros

In [14]:
e = np.zeros((2,3), dtype = int)
e

array([[0, 0, 0],
       [0, 0, 0]])

### Task: Create a numpy matrix of 3*2 integers, filled with ones

In [16]:
f = np.ones((2,3), dtype = int)
f

array([[1, 1, 1],
       [1, 1, 1]])

### Task: Create a numpy matrix of 3*2 integers, filled with random integers in [0, 10]

In [18]:
g = np.random.randint(0,10,(3,2), dtype = int)
g

array([[9, 7],
       [1, 8],
       [5, 9]])

### Task: Create a numpy matrix of 100 * 2, filled with random float value in [0, 1]

In [20]:
h = np.random.random((100,2))
h

array([[0.66662565, 0.55994525],
       [0.80746042, 0.05564104],
       [0.55473233, 0.23463657],
       [0.07403717, 0.21032786],
       [0.88877664, 0.70309789],
       [0.33618851, 0.55690612],
       [0.98093963, 0.70783636],
       [0.76991693, 0.55420483],
       [0.42573094, 0.98599521],
       [0.46781876, 0.40386738],
       [0.32623971, 0.83592143],
       [0.41617513, 0.66472828],
       [0.44932239, 0.9676482 ],
       [0.53129903, 0.41792366],
       [0.8529761 , 0.29235822],
       [0.40967132, 0.336542  ],
       [0.04891414, 0.97624652],
       [0.43393158, 0.98465314],
       [0.38977428, 0.82047825],
       [0.74383398, 0.33898696],
       [0.01399059, 0.47061362],
       [0.67005513, 0.5519067 ],
       [0.23694958, 0.46787541],
       [0.06488238, 0.95547613],
       [0.16897157, 0.2811786 ],
       [0.27764826, 0.48584258],
       [0.88126342, 0.05171202],
       [0.40762589, 0.36747667],
       [0.85018806, 0.76892661],
       [0.87913144, 0.59388655],
       [0.

### Task: Create a numpy matrix of 2 * 3 * 4, filled with integers from 1 to 24.

In [22]:
i = np.arange(1,24+1).reshape(2,3,4)
i

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

## Array Indexing

### Task: Let X be a numpy array, and X = np.array([1, 2, 3, 4, 5])

In [25]:
x = np.array([1,2,3,4,5])

### Task: Show the first element of X

In [27]:
x[0]

1

### Task: Show the last element of X

In [29]:
x[-1]

5

### Task: Show the first 3 elements of X

In [31]:
x[:3]

array([1, 2, 3])

### Task: Show the last 3 elements of X

In [33]:
x[-3:]

array([3, 4, 5])

### Task: Show the elements of X except the last one

In [35]:
x[:-1]

array([1, 2, 3, 4])

### Task: Let X be a numpy matrix with dimension 3 * 4, and filled from 0 to 11.

In [37]:
x = np.arange(12, dtype = int).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Task: Show the first row of X

In [39]:
x[0]

array([0, 1, 2, 3])

### Task: Show the first column of X

In [41]:
x[:,0]

array([0, 4, 8])

### Task: Show the first element of the first row of X

In [43]:
x[0,0]

0

### Task: Show the last row of X

In [45]:
x[-1]

array([ 8,  9, 10, 11])

### Task: Show the last column of X

In [47]:
x[:,-1]

array([ 3,  7, 11])

### Task: Show the last element of the last row of X

In [49]:
x[-1,-1]

11

### Task: Show all the rows except the last row of X

In [51]:
x[:-1]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### Task: Show all the columns except the last column of X

In [53]:
x[:,:-1]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

### Task: Show the first two elements of the first two rows

In [55]:
x[:2,:2]

array([[0, 1],
       [4, 5]])

## Array Statistics

### Task: Create a numpy array X, print the sum, mean, std, var, max, min of it

In [58]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Task: Create a numpy matrix X as n * m, print the sum, mean, std, var, max, min of the 1st row of it.

In [60]:
x.shape

print(x[0].sum())
print(x[0].mean())
print(x[0].std())
print(x[0].var())
print(x[0].max())
print(x[0].sum())


6
1.5
1.118033988749895
1.25
3
6


## Array Linear Algebra

###Task: Create two numpy matrix X with 2 * 2, and Y with 2 * 2. Practice Linear Algebra operations, such as +, -, *, .T, @, etc. 

In [63]:
x = np.arange(0,4,1).reshape(2,2)
y = np.arange(4,8,1).reshape(2,2)

In [64]:
x + y

array([[ 4,  6],
       [ 8, 10]])

In [65]:
x - y

array([[-4, -4],
       [-4, -4]])

In [66]:
x * y

array([[ 0,  5],
       [12, 21]])

In [67]:
x @ y

array([[ 6,  7],
       [26, 31]])

In [68]:
x @ y.T

array([[ 5,  7],
       [23, 33]])